
RUN set -x \
    && groupadd --system --gid 101 nginx \
    && useradd --system --no-create-home --uid 101 --gid nginx --groups www-data --home-dir /nonexistent --comment "nginx user" --shell /bin/false nginx

RUN apt-get update \
    && apt-get install -o Dpkg::Options::="--force-confold" -y nginx gettext-base \
    && rm -rf /var/lib/apt/lists/*
